routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /membership/: members/membership
  
  #Individual Pages
  ##  /about/: about
  /contact/bug-track/: bug-track
  /contact/discord/: discord
  /contact/requests/: requests
  /legal/privacy/: privacy
  /legal/AUP/: AUP
  /legal/olt-tos/: TOS

  /featured/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    limit: 6
    template: godo-template-featured
    # Optional for metada for seo
    data: page.home-featured

  /archive/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    limit: all
    template: godo-archive

  /grid/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    limit: 6
    template: godo-template-grid

  /sidebar/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    limit: 6
    template: godo-template-sidebar

  /medium/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    template: godo-template-medium
    limit: 6

  /featured-slider/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    template: godo-template-featured-slider

  /photographer/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    template: godo-template-photographer
    limit: 6

  /personal/:
    template: godo-home-personal
    data: page.godo-personal

  /personal-portfolio/:
    template: godo-home-personal-portfolio
    data: page.godo-personal-portfolio
    
  #Load Order FAQ
  /load-order/faq/:
    controller: channel
    filter: 'tag:[faq]'
    limit: all
    template: godo-home-kusi-doc
    data: page.kusi-doc
    
  #Load Order Survival Guide Changelog
  /load-order/lo-survival-guide/changelog/:
    controller: channel
    filter: 'tag:[survival-guide-changelog]'
    limit: all
    template: godo-home-kusi-doc
    data: page.kusi-doc

collections:
  # PortFolio
  #/portafolio/:
  #  permalink: /portafolio/{slug}/
  #  filter: 'tag:[hash-portfolio]'
  #  data: page.porftfolio
  #  template: godo-template-portfolio
  #  limit: all

  # Podcast
  #/podcast/:
  #  permalink: /podcast/{slug}/
  #  filter: 'tag:[hash-podcast]'
  #  data: page.podcast
  #  template: godo-podcast
  #  limit: 10
  
  # Writing Binge
  /writing-binge/:
    permalink: /writing-binge/{year}/{slug}/
    filter: 'tag:[november-writing-binge,onowribi,nanowrimo]'

  #Ugh.
  /mods/ugh/:
    permalink: /mods/ugh/{slug}/
    filter:'tag:[hash-ugh-series]'
    template: godo-home-kusi-doc
    
  # Skyrim Mods
  /mods/skyrim/:
    permalink: /mods/skyrim/{slug}/
    filter: 'tag:[skyrim-se-mods]'
    
  # Mod Releases
  /mods/relz/:
    permalink: /mods/relz/{slug}/
    filter: 'tag:[hash-release]'

  # Mod Ports
  /mods/ports/:
    permalink: /mods/ports/{slug}/
    filter: 'tag:[hash-ports,xbox-ports]'

  #Companion Mods
  /mods/companions/:
    permalink: /mods/companions/{slug}/
    filter: 'tag:[hash-companion-mods]'
    
  # Mods
  /mods/:
    permalink: /mods/{slug}/
    filter: 'tag:[hash-mods,mod-release,mod-update]'
    data: page.mods
    template: index
    limit: all
    
  # Mod Tutorials
  /mod-dev/tutorials/:
    permalink: /mod-dev/tutorials/{slug}/
    filter: 'tag:[modding-tutorials,tutorials]'
    limit: 5
    template: index
  
  #Mod Development Blog
  /mod-dev/:
    permalink: /mod-dev/{slug}/
    filter: 'tag:[hash-modding-journey,creation-kit]'
    template: godo-template-featured-slider
    limit: 12

  # Documentation
  /mods/docs/:
    permalink: /mods/docs/{slug}/
    filter: 'tag:[hash-kusi-doc]'
    template: godo-home-kusi-doc
    
  #Load Order Spotlight
  /load-order/spotlight/:
    permalink: /load-order/spotlight/{slug}/
    filter: 'tag:[load-order-spotlight]'
    
  # Load order FAQ Articles to Specific Questions
  /load-order/faq/articles/:
    permalink: /load-order/faq/{slug}/
    filter: 'tag:[hash-asq,faq]'
    template: godo-home-kusi-doc
    limit: 6

  #Load Order
  /load-order/:
    permalink: /load-order/{slug}/
    filter: 'tag:[load-order-survival,load-order-framework,load-order]'
    template: godo-home-kusi-doc
    limit: 12

  # Default
  /:
    permalink: /{slug}/
    filter: 'tag:-[hash-portfolio,hash-kusi-doc,hash-podcast,hash-docs,load-order,load-order-framework,load-order-spotlight,load-order-survival,modding-journey,modding-tutorials,hash-mods,mod-release,mod-update,hash-companion-mods,skyrim-se-mods,hash-ugh-series,november-writing-binge,nanowrimo,onowribi,faq,hash-asq,hash-ports,wasteland-imports,hash-wip,hash-release]'
    template: godo-template-featured
    limit: 6

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
