routes:
  # Members
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /membership/: members/membership
  
  #Individual Pages
  ##  /about/: about
  #/contact/bug-track/: bug-track
  #/contact/discord/: discord
  #/contact/requests/: requests
  #/odds-mods/: odds-mods
  
  #Load Order FAQ
  /load-order/faq/:
    controller: channel
    filter: 'tag:[faq,hash-asq]'
    limit: all
    template: godo-archive-faq
    data: page.lo-faq
    
  #Load Order Changelog
  /load-order/survival-guide/changelog/:
    filter: 'tag:[survival-guide-changelog]'
    limit: all
    template: godo-archive-changelog

  # Mod Ports
  /mods/ports/:
    filter: 'tag:[hash-ports,xbox-ports]'
    limit: all
    template: godo-archive-mods
  
  # Mods
  /mods/:
    filter: 'tag:[hash-mods]'
    template: godo-archive-mods
    limit: all

  # Mod Tutorials
  /mod-dev/tutorials/:
    filter: 'tag:[modding-tutorials,tutorials,creation-kit]'
    limit: 12
    template: godo-template-medium

  /featured/:
    controller: channel
    filter: 'tag:-[faq,hash-docs,hash-mods]'
    limit: 10
    template: index
    data: page.home-featured
  
  /archive/:
    controller: channel
    filter: 'tag:-[faq,hash-docs]'
    limit: all
    template: index
    
  /:
    template: simply-home
    data: page.simply-home

collections:
  # Mod Releases
  /mods/relz/:
    permalink: /mods/relz/{slug}/
    filter: 'tag:[hash-relz,mod-release]'
    template: godo-template-medium
    
  #Mod Development Blog
  /mod-dev/:
    permalink: /mod-dev/{slug}/
    filter: 'tag:[modding-journey,hash-modding-journey,xbox,playthrough,work-in-progress]'
    data: page.mod-development
    template: godo-template-medium
    limit: all

  #Load Order Spotlight
  /load-order/spotlight/:
    permalink: /load-order/spotlight/{slug}/
    filter: 'tag:[load-order-spotlight]'
    
  # Load order FAQ Articles to Specific Questions
  /load-order/faq/articles/:
    permalink: /load-order/faq/{slug}/
    filter: 'tag:[hash-asq]'
    data: page.lo-faq
    template: godo-archive-faq
    limit: all

  #Load Order
  /load-order/:
    permalink: /load-order/{slug}/
    filter: 'tag:[hash-load-order,load-order-survival-guide]'
    template: godo-archive

  # Documentation
  /mods/docs/:
    permalink: /mods/docs/{slug}/
    filter: 'tag:[hash-docs]'
    template: godo-archive
    limit: 5

  # Default
  /:
    permalink: /{slug}/
    filter: 'tag:-[hash-docs,load-order,load-order-framework,load-order-spotlight,load-order-survival,modding-journey,modding-tutorials,hash-mods,mod-release,mod-update,hash-companion-mods,skyrim-se-mods,hash-ugh-series,november-writing-binge,nanowrimo,onowribi,faq,hash-asq,hash-ports,wasteland-imports,hash-wip,hash-release]'

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/